apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
        - name: ums
          image: akmazura/wallet-ums:latest
          ports:
            - containerPort: 8080 # HTTP
            - containerPort: 7001 # GRPC